version: '3.7'

services:

  web:
    container_name: il-web
    image: il-web:${TAG}
    env_file: .env
    build:
      context: web
      args:
        DOMAIN: ${DOMAIN}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    depends_on:
      - dashboard
    volumes:
      - st:/app/il
      - /etc/letsencrypt:/etc/letsencrypt

  dashboard:
    container_name: il-dashboard
    image: il-dashboard:${TAG}
    env_file: .env
    build:
      context: dashboard
    restart: unless-stopped
    command: /usr/local/bin/entrypoint dashboard-local
    volumes:
      - st:/app/st
      - db:/app/db

volumes:
  st:
    name: il-static
  db:
    name: il-db

networks:
  default:
    external:
      name: traefik_il
