# Generated by Django 3.1.7 on 2021-03-08 08:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='¿Quiénes somos?')),
                ('recording', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Estudio Online')),
                ('contact', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='Nombre')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descripción')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Icono')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.content', verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='Nombre')),
                ('slides', models.TextField(help_text='Un link por línea', verbose_name='Links de youtube')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.content', verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='Nombre')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descripción')),
                ('img', models.ImageField(blank=True, null=True, upload_to='members/', verbose_name='Imágen')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.content', verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
            },
        ),
    ]
