# Generated by Django 3.1.7 on 2021-03-26 20:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20210321_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='project',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Ivory Live'),
        ),
    ]
